feat: Teacher account tab
ocadotechnology/codeforlife-portal-frontend pull request #82
Opened 2024-12-31 11:58 UTC by faucomte97

2025-01-07 12:04 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 0 of 10 files reviewed, 15 unresolved discussions (waiting on @faucomte97)

___
*[`src/components/form/UpdateAccountForm.tsx` line 186 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-b4LVDlD-nAk445rM:-OG-b4LVDlD-nAk445rN:b-z2bbgb) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/components/form/UpdateAccountForm.tsx#L186)):*
> ```XML
>           ])
> 
>           let passwordSchema = indyPasswordSchema.concat(nullableSchema)
> ```

just make the password field not required
___
*[`src/components/form/UpdateAccountForm.tsx` line 191 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-b9M4BUQwHvhfEwle:-OG-b9M4BUQwHvhfEwlf:b-z2bbgb) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/components/form/UpdateAccountForm.tsx#L191)):*
> ```XML
>             passwordSchema = studentPasswordSchema
>           } else if (user.teacher) {
>             passwordSchema = teacherPasswordSchema.concat(nullableSchema)
> ```

just make the password field not required
___
*[`src/pages/teacherDashboard/account/Account.tsx` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-bu4s1PSUJVHyl8qf:-OG-bu4s1PSUJVHyl8qg:b2meiif) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Account.tsx#L14)):*
> ```XML
> export interface AccountProps {
>   authUser: SchoolTeacherUser<RetrieveUserResult>
>   view?: "otp" | "backupTokens"
> ```

"otp" | "otp-bypass-tokens"
___
*[`src/pages/teacherDashboard/account/Account.tsx` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-c_eo3KEoCemVY1bT:-OG-c_eo3KEoCemVY1bU:brxn462) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Account.tsx#L20)):*
> ```XML
>   if (view) {
>     return {
>       otp: <Setup2FA user={authUser} />,
> ```

`otp: <OTP user={authUser} />`

need to keeps names consistent or code will get confusing to read. [example](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e2a87e796f00828812ee48b53bfad7299c94be68/src/pages/teacherDashboard/classes/Classes.tsx#L30)
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dHJe33JwYyMqPhy8:-OG-dHJe33JwYyMqPhy9:b-610dlp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L12)):*
> ```XML
> import { useListAuthFactorsQuery } from "../../../api/authFactor"
> 
> const Setup2FAForm: FC<{ user: SchoolTeacherUser<RetrieveUserResult> }> = ({
> ```

rename to OTP
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dPMZ2i_jzphCh2UT:-OG-dPMZ2i_jzphCh2UU:b-mzlwq8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L16)):*
> ```XML
> }) => {
>   const navigate = useNavigate()
>   const theme = useTheme()
> ```

do not use theme hook
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dLCR5HiCmybLkqkn:-OG-dLCR5HiCmybLkqko:brxcbbu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L19)):*
> ```XML
>   return (
>     <>
>       <Button
> ```

use link button
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dRCNClDAEN2TqCYf:-OG-dRCNClDAEN2TqCYg:b-fohvme) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L27)):*
> ```XML
>           )
>         }}
>         sx={{ marginTop: theme.spacing(3) }}
> ```

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 53 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dbM163OSpH6SsyUr:-OG-dbM163OSpH6SsyUs:b-oq3b23) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L53)):*
> ```XML
>   return (
>     <Grid container>
>       <Grid sm={6} marginTop={theme.spacing(4)}>
> ```

just 4
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 71 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-demm7qkYC1antc0M:-OG-demm7qkYC1antc0N:b-fohvme) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L71)):*
> ```XML
>             )
>           }}
>           sx={{ marginTop: theme.spacing(3) }}
> ```

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 80 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dfm98yXLY4-2CA80:-OG-dfm98yXLY4-2CA81:b-fohvme) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L80)):*
> ```XML
>           color="error"
>           mb={0}
>           sx={{ marginTop: theme.spacing(3) }}
> ```

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 85 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dh9C7mHB0-MKP2XA:-OG-dh9C7mHB0-MKP2XB:b-oq3b23) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L85)):*
> ```XML
>         </Typography>
>       </Grid>
>       <Grid sm={6} marginTop={theme.spacing(4)}>
> ```

just 4
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 98 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dgg0DR-UJkV7MMVx:-OG-dgg0DR-UJkV7MMVy:b-fohvme) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L98)):*
> ```XML
>           className="alert"
>           endIcon={<ErrorOutlineOutlined />}
>           sx={{ marginTop: theme.spacing(3) }}
> ```

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
___
*[`src/components/form/UpdateAccountForm.tsx` line 158 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-bBXY1Z1tuGu7E9Fr:-OG-bBXY1Z1tuGu7E9Fs:bxc7mf4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cec91ac4f10b4492f9b995f96019da37727ed8f3/src/components/form/UpdateAccountForm.tsx#L158)):*
> ```X [...]

2025-01-07 12:05 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 0 of 10 files reviewed, 16 unresolved discussions (waiting on @faucomte97)

___
*[`src/pages/teacherDashboard/account/Setup2FA.tsx` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dtPH8K_yEl1ravan:-OG-dtPH8K_yEl1ravao:b-610dlp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Setup2FA.tsx#L9)):*
> ```XML
> }
> 
> const Setup2FA: FC<Setup2FAProps> = () => {
> ```

rename to OTP


<!-- Sent from Reviewable.io -->

2025-01-07 12:06 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 0 of 10 files reviewed, 17 unresolved discussions (waiting on @faucomte97)

___
*[`src/components/form/UpdateAccountForm.tsx` line 135 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-e7H4-nwjpXLIK1BN:-OG-e7H4-nwjpXLIK1BO:b2nhcva) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/components/form/UpdateAccountForm.tsx#L135)):*
> ```XML
>                       },
>                     })
>                   })
> ```

DRY



_Code quote:_
```XML
                    navigate(teacherLoginPath, {
                      state: {
                        notifications: messages.map(message => ({
                          props: { children: message },
                        })),
                      },
                    })
                  })
                  // TODO: Check what happens here - is the field still updated?
                  .catch(() => {
                    navigate(".", {
                      replace: true,
                      state: {
                        notifications: [
                          {
                            props: {
                              error: true,
                              children: "Failed to log you out.",
                            },
                          },
                        ],
                      },
                    })
                  })
```


<!-- Sent from Reviewable.io -->

2025-01-07 12:08 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 0 of 10 files reviewed, 18 unresolved discussions (waiting on @faucomte97)

___
*[`src/components/form/UpdateAccountForm.tsx` line 92 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-eHVt56W0rTmQrBHM:-OG-eHVt56W0rTmQrBHN:b-7bz6hc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/components/form/UpdateAccountForm.tsx#L92)):*
> ```XML
>             } else if (isDirty(values, initialValues, "last_name")) {
>               arg.last_name = values.last_name
>             }
> ```

this is why you can only update first name or last name. should not be an elif. In fact, why are these checks even needed? Rather, just check if the user is a teacher and add first name and last name. 



_Code quote:_
```XML
            } else if (isDirty(values, initialValues, "first_name")) {
              arg.first_name = values.first_name
            } else if (isDirty(values, initialValues, "last_name")) {
              arg.last_name = values.last_name
            }
```


<!-- Sent from Reviewable.io -->

2025-01-08 18:05 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 0 of 10 files reviewed, 18 unresolved discussions (waiting on @SKairinos)

___
*[`src/pages/teacherDashboard/account/Account.tsx` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-bu4s1PSUJVHyl8qf:-OG5V3X980nV_au8_BGi:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Account.tsx#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

"otp" | "otp-bypass-tokens"
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Account.tsx` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-c_eo3KEoCemVY1bT:-OG5VrJsEUY_vmaG6lUO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Account.tsx#L20)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

`otp: <OTP user={authUser} />`

need to keeps names consistent or code will get confusing to read. [example](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e2a87e796f00828812ee48b53bfad7299c94be68/src/pages/teacherDashboard/classes/Classes.tsx#L30)
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/BackupTokens.tsx` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-c8gsBvUx5H8luGzl:-OG5W4kS6JreG3WboDwM:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/BackupTokens.tsx#L9)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

OtpBypassToken. rename everywhere
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dHJe33JwYyMqPhy8:-OG5WX67EOKwIBvhmn4d:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L12)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to OTP
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dPMZ2i_jzphCh2UT:-OG5W_X45lMwT7XeqokS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

do not use theme hook
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dLCR5HiCmybLkqkn:-OG5WvHn4rXBo1YSksd_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L19)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use link button
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dRCNClDAEN2TqCYf:-OG5WyDH6J7OgCzGwacl:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L27)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 53 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dbM163OSpH6SsyUr:-OG5X2pDBiFI4acLK7pp:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L53)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just 4
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 71 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-demm7qkYC1antc0M:-OG5XCNY06o7_GracsyS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L71)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 80 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dfm98yXLY4-2CA80:-OG5XCcR1pLb-iyE9g3x:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L80)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 85 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dh9C7mHB0-MKP2XA:-OG5XCrM5DDDmfkjwHe-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L85)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just 4
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Manage2FAForm.tsx` line 98 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dgg0DR-UJkV7MMVx:-OG5XDAC8i1-5FSyzSTf:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Manage2FAForm.tsx#L98)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just use [mt](https://mui.com/system/getting-started/the-sx-prop/?srsltid=AfmBOoqyzto7TNcLztvbA0i-fj39E-aa3hR7NUloLZKf1VTXeSMMaGag#spacing)
</blockquote></details>

Done.
___
*[`src/pages/teacherDashboard/account/Setup2FA.tsx` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-dtPH8K_yEl1ravan:-OG5XTg7BZEmSFylWIBs:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/pages/teacherDashboard/account/Setup2FA.tsx#L9)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to OTP
</blockquote></details>

Done.
___
*[`src/components/form/UpdateAccountForm.tsx` line 92 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-eHVt56W0rTmQrBHM:-OG64T18AcflTkwEVoZn:b-b99pvc) ([raw file](https://github. [...]

2025-01-28 17:53 UTC, SKairinos requested changes
> Reviewed 1 of 10 files at r1, 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 2 of 12 files reviewed, 22 unresolved discussions (waiting on @faucomte97)

___
*[`src/components/form/UpdateAccountForm.tsx` line 107 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhzcng9naefla9ox2q:-OHhzcnh4FXlClUDm3Tg:b-3tjkqc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L107)):*
> ```XML
> 
>             if (isEmailDirty || isPasswordDirty) {
>               let loginPath = generatePath(paths.login.indy._)
> ```

no need to generate this path since the path does not have any args



_Code quote:_
```XML
generatePath(paths.login.indy._)
```
___
*[`src/components/form/UpdateAccountForm.tsx` line 110 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhzelI60sw59vxD83y:-OHhzelI60sw59vxD83z:b-3tjkqc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L110)):*
> ```XML
> 
>               if (authUser.student) {
>                 loginPath = generatePath(paths.login.student._)
> ```

no need to generate this path since the path does not have any args



_Code quote:_
```XML
generatePath(paths.login.student._)
```
___
*[`src/components/form/UpdateAccountForm.tsx` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhzfnKCnhVSHYyhArL:-OHhzfnKCnhVSHYyhArM:b-3tjkqc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L112)):*
> ```XML
>                 loginPath = generatePath(paths.login.student._)
>               } else if (authUser.teacher) {
>                 loginPath = generatePath(paths.login.teacher._)
> ```

no need to generate this path since the path does not have any args



_Code quote:_
```XML
generatePath(paths.login.teacher._)
```
___
*[`src/components/form/UpdateAccountForm.tsx` line 177 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi-n0J5kkwjqy0S4kC:-OHi-n0J5kkwjqy0S4kD:b-s0orz5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L177)):*
> ```XML
>                     })
>                   })
>               }
> ```

Undo all the FE logic you wrote about checking if the email and/or password is dirty and then logging the user out. Instead, we should make a separate BE task where the following happens:

1. The FE calls the UpdateUserSerializer on the BE.
2. The BE will check if any credential fields have been updated (email, password)
3. The BE will use [Django's logout util](https://docs.djangoproject.com/en/5.1/topics/auth/default/#django.contrib.auth.logout) to delete the user's session from the session table.
4. The BE will return a specific status code (maybe 403 unauthorized?) that will inform the FE it needs to redirect to the appropriate login page.

The responsibility of logging out should be on the BE for security. If it's on the FE, then it's technically possible to block the logout HTTP call to the BE using a traffic interceptor - we shouldn't allow for this possibility.

Please also add a TODO here in the code to handle the logout scenario in the cases where the BE force logs the user out.



_Code quote:_
```XML
            if (isEmailDirty || isPasswordDirty) {
              let loginPath = generatePath(paths.login.indy._)

              if (authUser.student) {
                loginPath = generatePath(paths.login.student._)
              } else if (authUser.teacher) {
                loginPath = generatePath(paths.login.teacher._)
              }

              if (isEmailDirty) {
                void logout(null)
                  .unwrap()
                  .then(() => {
                    messages.push(
                      "Your email will be changed once you have verified it, until then you can still log in with your old email.",
                    )
                    navigate(loginPath, {
                      state: {
                        notifications: messages.map(message => ({
                          props: { children: message },
                        })),
                      },
                    })
                  })
                  // TODO: Check what happens here - is the field still updated?
                  .catch(() => {
                    navigate(".", {
                      replace: true,
                      state: {
                        notifications: [
                          {
                            props: {
                              error: true,
                              children: "Failed to log you out.",
                            },
                          },
                        ],
                      },
                    })
                  })
              }
              if (isPasswordDirty) {
                void logout(null)
                  .unwrap()
                  .then(() => {
                    messages.push(
                      "Going forward, please log in using your new password.",
                    )
                    navigate(loginPath, {
                      state: {
                        notifications: messages.map(message => ({
                          props: { children: message },
                        })),
                      },
                    })
                  })
                  .catch(() => {
                    navigate(".", {
                      replace: true,
                      state: {
                        notifications: [
                          {
                            props: {
                              error: true,
                              children: "Failed to log you out.",
                            },
                          },
                        ],
                      },
                    })
                  })
              }
```
___
*[`src/components/form/DeleteAccountForm.tsx` line 135 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhyTaz2Agqfp9zFewb:-OHhyTaz2Agqfp9zFewc:b-prp7tz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/DeleteAccountForm.tsx#L135)):*
> ```XML
>           className="alert"
>           endIcon={<DeleteOutlineIcon />}
>           sx={theme => ({ marginTop: theme.spacing(3) })}
> ```

just do `sx={{ marginTop: 3 }}`. It's equivalent



_Code quote:_
```XML
sx={theme => ({ marginTop: theme.spacing(3) })}
```


<!-- Sent from Reviewable.io -->

2025-01-28 17:59 UTC, SKairinos requested changes
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 3 of 12 files reviewed, 22 unresolved discussions (waiting on @faucomte97)

___
*[`src/pages/studentAccount/StudentAccount.tsx` line 8 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi31Iu4uIXMBqI07-B:-OHi31Iu4uIXMBqI07-C:bc4s3ne) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/pages/studentAccount/StudentAccount.tsx#L8)):*
> ```XML
> import { handleResultState } from "codeforlife/utils/api"
> 
> import * as forms from "../../components/form"
> ```

Let's reserve the `forms` import for the form components in the cfl package.
`import * as forms from "codeforlife/components/form"`
Instead, import like so:
`import { DeleteAccountForm, UpdateAccountForm } from "../../components/form"`



_Code quote:_
```XML
import * as forms from "../../components/form"
```
___
*[`src/components/form/UpdateAccountForm.tsx` line 196 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi2nACB5jVwuTmOl80:-OHi2nACB5jVwuTmOl81:b-ymam2r) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L196)):*
> ```XML
>           ])
> 
>           let passwordSchema = indyPasswordSchema.concat(nullableSchema)
> ```

can you show me on a call why this needs to be made nullable? confused as to what is failing and why this is needed.



_Code quote:_
```XML
indyPasswordSchema.concat(nullableSchema)
```
___
*[`src/components/form/UpdateAccountForm.tsx` line 236 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi2Zc42MaVjpYM2d3K:-OHi2Zc42MaVjpYM2d3L:b-w2ufq0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L236)):*
> ```XML
>               )}
>               <forms.SubmitButton
>                 sx={theme => ({ marginTop: theme.spacing(3) })}
> ```

see previous comment



_Code quote:_
```XML
 sx={theme => ({ marginTop: theme.spacing(3) })}
```


<!-- Sent from Reviewable.io -->

2025-01-28 18:02 UTC, SKairinos requested changes
> Reviewed 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 8 of 12 files reviewed, 10 unresolved discussions (waiting on @faucomte97)

___
*[`src/pages/studentJoinClass/StudentJoinClass.tsx` line 46 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi3aKaCGCA5hmwSKtA:-OHi3aKaCGCA5hmwSKtB:bmuuh2l) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e2a87e796f00828812ee48b53bfad7299c94be68/src/pages/studentJoinClass/StudentJoinClass.tsx#L46)):*
> ```XML
>               indyUser={{
>                 id: user.id,
>                 requesting_to_join_class: user.requesting_to_join_class!.id,
> ```

why was this removed?



_Code quote:_
```XML
  requesting_to_join_class: user.requesting_to_join_class!.id,
```


<!-- Sent from Reviewable.io -->

2025-01-31 12:01 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 6 of 12 files reviewed, 10 unresolved discussions (waiting on @SKairinos)

___
*[`src/components/form/UpdateAccountForm.tsx` line 135 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OG-e7H4-nwjpXLIK1BN:-OHwC8eG5QcBk10Rf5n0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a342c4096280c05d83669f71e4190090649c07e7/src/components/form/UpdateAccountForm.tsx#L135)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

DRY
</blockquote></details>

Done.
___
*[`src/components/form/UpdateAccountForm.tsx` line 107 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhzcng9naefla9ox2q:-OHw8uSm6vU4W1YXUu-z:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L107)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to generate this path since the path does not have any args
</blockquote></details>

Done.
___
*[`src/components/form/UpdateAccountForm.tsx` line 110 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhzelI60sw59vxD83y:-OHw8vSu9uxTf7PJX2f8:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L110)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to generate this path since the path does not have any args
</blockquote></details>

Done.
___
*[`src/components/form/UpdateAccountForm.tsx` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhzfnKCnhVSHYyhArL:-OHw8vvF53_fw73m9HHL:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L112)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to generate this path since the path does not have any args
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-31 12:41 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: 5 of 15 files reviewed, 10 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`src/pages/studentAccount/StudentAccount.tsx` line 8 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi31Iu4uIXMBqI07-B:-OHwN5Am7Eq6iTg4MEHI:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/pages/studentAccount/StudentAccount.tsx#L8)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Let's reserve the `forms` import for the form components in the cfl package.
`import * as forms from "codeforlife/components/form"`
Instead, import like so:
`import { DeleteAccountForm, UpdateAccountForm } from "../../components/form"`
</blockquote></details>

Done.
___
*[`src/pages/studentJoinClass/StudentJoinClass.tsx` line 46 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi3aKaCGCA5hmwSKtA:-OHwN6UsAJQLuZjFZkEW:b-phha1i) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e2a87e796f00828812ee48b53bfad7299c94be68/src/pages/studentJoinClass/StudentJoinClass.tsx#L46)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why was this removed?
</blockquote></details>

Was stopping the Student Join Class page from loading, was complaining about the arg for some reason. I removed it and it seems to still work fine :shrug: 
___
*[`src/components/form/DeleteAccountForm.tsx` line 135 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHhyTaz2Agqfp9zFewb:-OHwK3zl8xPjMoJugjMZ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/DeleteAccountForm.tsx#L135)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just do `sx={{ marginTop: 3 }}`. It's equivalent
</blockquote></details>

Done.
___
*[`src/components/form/UpdateAccountForm.tsx` line 177 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi-n0J5kkwjqy0S4kC:-OHwLhtT8lemeeaNWXvT:b2kbnoq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L177)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Undo all the FE logic you wrote about checking if the email and/or password is dirty and then logging the user out. Instead, we should make a separate BE task where the following happens:

1. The FE calls the UpdateUserSerializer on the BE.
2. The BE will check if any credential fields have been updated (email, password)
3. The BE will use [Django's logout util](https://docs.djangoproject.com/en/5.1/topics/auth/default/#django.contrib.auth.logout) to delete the user's session from the session table.
4. The BE will return a specific status code (maybe 403 unauthorized?) that will inform the FE it needs to redirect to the appropriate login page.

The responsibility of logging out should be on the BE for security. If it's on the FE, then it's technically possible to block the logout HTTP call to the BE using a traffic interceptor - we shouldn't allow for this possibility.

Please also add a TODO here in the code to handle the logout scenario in the cases where the BE force logs the user out.
</blockquote></details>

Removed, not sure what you meant regarding the last TODO.
Also, what about the different notifications based on the field that was updated? Can the BE handle that?
___
*[`src/components/form/UpdateAccountForm.tsx` line 196 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi2nACB5jVwuTmOl80:-OHwMYMF3XigWNuznF72:br5o95q) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L196)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

can you show me on a call why this needs to be made nullable? confused as to what is failing and why this is needed.
</blockquote></details>

Because then this happens

![image.png](https://files.reviewableusercontent.io/images/reviewable/33633200/0wlcGMGwFKiovDj3XjBZs2Ww/image.png)

Yup is like "this field isn't nullable so I'll check it against its schema" even though it's not a required field. Blocks the user from using the form when they don't want to update their password.

Can call if needed
___
*[`src/components/form/UpdateAccountForm.tsx` line 236 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82#-OHi2Zc42MaVjpYM2d3K:-OHwN5gCAP-dEh7OLHBz:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/a2ae75a0d754f02e712d17a47d5575ee9ec1573f/src/components/form/UpdateAccountForm.tsx#L236)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see previous comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-04 09:57 UTC, SKairinos approved these changes
> Reviewed 1 of 13 files at r1, 2 of 13 files at r2, 2 of 2 files at r3, 4 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2025-02-04 11:44 UTC, SKairinos approved these changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/82)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2025-02-04 11:45 UTC, merged